services:
  # Сервис для базы данных
  db:
    image: postgres:16
    container_name: rssagg_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${PG_USER} --dbname ${PG_DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    expose:
      - "5432"
    env_file:
      - .env
  # Сервис для приложения на Go
  app:
    build: .
    restart: always
    container_name: rssagg_app
    environment:
      DB_URL: ${DB_URL}
    command: sh -c 'echo ${DB_URL} && go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir ./sql/schema postgres ${DB_URL} up && /app/rssagg'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  # Nginx сервер
  nginx:
    image: nginx:latest
    container_name: rssagg_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - /etc/nginx/ssl/ca.crt:/etc/ssl/ca.crt:ro
      - /etc/nginx/ssl/certs/:/etc/ssl/certs/:ro
      - /etc/nginx/ssl/private/:/etc/ssl/private/:ro
      - static_value:/home/root/rss-agg/static/
    depends_on:
      - app
      - db
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_data:
  static_value:
